// Auto-generated by CMake
#pragma once

#include <cstdint>
#include <string_view>

namespace SF::Engine {
constexpr uint8_t Engine_VERSION_MAJOR = 2025;
constexpr uint8_t Engine_VERSION_MINOR = 12;
constexpr uint8_t Engine_VERSION_PATCH = 2;
constexpr std::string_view Engine_VERSION = "2025.12.2";
} // namespace SF::Engine
